name: Lint workflow files

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint:
    name: 'Lint'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Download actionlint
        id: download_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Enable actionlint matcher
        id: enable_actionlint_matcher
        run: echo "::add-matcher::.github/actionlint-matcher.json"
        shell: bash

      - name: Lint workflow files
        run: ${{ steps.download_actionlint.outputs.executable }} -color
