name: Lint workflow files

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened # no need on 'reopened'
      - synchronize
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  lint:
    name: 'Lint'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Download actionlint
        id: download_actionlint
        shell: bash
        run: |
          bash <(curl "https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash")

      - name: Enable actionlint matcher
        shell: bash
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

      - name: Lint workflow files
        shell: bash
        run: |
          ${{ steps.download_actionlint.outputs.executable }} -color
